SET LOCK_MODE 3;              
;             
CREATE USER IF NOT EXISTS SA SALT '83948e12465e79fe' HASH '6c7b6c9239a523d01c977ef21376837853393f2b3cb5526297c3b31195877b5f' ADMIN;           
CREATE SEQUENCE PUBLIC.JPA_CANDLE_ID START WITH 1 BELONGS_TO_TABLE;       
CREATE SEQUENCE PUBLIC.JPA_SYMBOL_ID START WITH 1 BELONGS_TO_TABLE;           
CREATE SEQUENCE PUBLIC.JPA_RATE_ID START WITH 1 BELONGS_TO_TABLE;         
CREATE CACHED TABLE PUBLIC.JPA_SYMBOL(
    ID INT DEFAULT (NEXT VALUE FOR PUBLIC.JPA_SYMBOL_ID) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.JPA_SYMBOL_ID,
    NAME VARCHAR(6) NOT NULL,
    DURATION BIGINT NOT NULL
);     
ALTER TABLE PUBLIC.JPA_SYMBOL ADD CONSTRAINT PUBLIC.JPA_SYMBOL_PK PRIMARY KEY(ID);            
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.JPA_SYMBOL;              
CREATE CACHED TABLE PUBLIC.JPA_CANDLE(
    ID BIGINT DEFAULT (NEXT VALUE FOR PUBLIC.JPA_CANDLE_ID) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.JPA_CANDLE_ID,
    DATETIME TIMESTAMP,
    OPEN DOUBLE NOT NULL,
    HIGH DOUBLE NOT NULL,
    LOW DOUBLE NOT NULL,
    CLOSE DOUBLE NOT NULL,
    VOLUME BIGINT NOT NULL,
    SYMBOL_ID INT NOT NULL
); 
ALTER TABLE PUBLIC.JPA_CANDLE ADD CONSTRAINT PUBLIC.JPA_CANDLE_PK PRIMARY KEY(ID);            
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.JPA_CANDLE;              
CREATE INDEX PUBLIC.JPA_CANDLE_INDEX_ON_DATETIME ON PUBLIC.JPA_CANDLE(DATETIME);              
CREATE INDEX PUBLIC.JPA_CANDLE_INDEX_ON_SYMBOL_ID ON PUBLIC.JPA_CANDLE(SYMBOL_ID);            
CREATE CACHED TABLE PUBLIC.JPA_RATE(
    ID BIGINT DEFAULT (NEXT VALUE FOR PUBLIC.JPA_RATE_ID) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.JPA_RATE_ID,
    SYMBOL_ID INT,
    DATETIME TIMESTAMP,
    BID DOUBLE NOT NULL,
    ASK DOUBLE NOT NULL
);     
ALTER TABLE PUBLIC.JPA_RATE ADD CONSTRAINT PUBLIC.JPA_RATE_PK PRIMARY KEY(ID);
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.JPA_RATE;
CREATE INDEX PUBLIC.JPA_RATE_INDEX_ON_RATE_DATETIME ON PUBLIC.JPA_RATE(DATETIME);             
CREATE INDEX PUBLIC.JPA_RATE_INDEX_ON_SYMBOL_ID ON PUBLIC.JPA_RATE(SYMBOL_ID);
ALTER TABLE PUBLIC.JPA_SYMBOL ADD CONSTRAINT PUBLIC.JPA_SYMBOL_UNIQUE_SYMBOL_DURATION UNIQUE(NAME, DURATION); 
